### ISSUE TITLE
Not showing questions

### ISSUE THREAD

**Issue by Krejzu** [asiddiqi18/Trivia-Plugin#2]
So bassicaly I installed Venture Chat and now trivia isnt showing questions in chat. ;v

**Comment by asiddiqi18** [comment]
> 
> 
> So bassicaly I installed Venture Chat and now trivia isnt showing questions in chat. ;v

Hey Krejzu. I'll take a look and get back to you.

**Comment by asiddiqi18** [comment]
I was able to install Venture Chat on a test server, and I didn't experience any issues with the Trivia plugin. Could you send your Venture Chat config files so I can replicate the issue?
