### ISSUE TITLE
Plugin don't load

### ISSUE THREAD

**Issue by cantorthiagofelipe** [asiddiqi18/Trivia-Plugin#4]
![image](https://user-images.githubusercontent.com/102884950/169371089-8adaec4a-0143-4133-ac47-5bd254dac555.png)

**Comment by asiddiqi18** [comment]
Thanks for bringing up this issue. Currently, the plugin is configured to run on only Minecraft version 1.18, and running it on an older version (in your case, 1.17) will cause this error. I'll release a patch soon so that this plugin is also compatible with 1.17.

**Comment by asiddiqi18** [comment]
New release should support 1.17 now
